import React, { useEffect, useState } from "react";
import { apiFetch, parseApiError } from "utils/api";
import { MappingRow, TradingPartner } from "types/tradingPartner";
const API_BASE = "/trading-partners";
const defaultMapping = (partnerId: string): MappingRow => ({ partner_id: partnerId, source_field: "", target_field: "", transform_type: "DIRECT", transform_config: {}, is_active: true });
export default function MappingSection({ partner, onBanner }: { partner: TradingPartner; onBanner: (text: string) => void; }) {
  const [rows, setRows] = useState<MappingRow[]>([]); const [form, setForm] = useState<MappingRow>(defaultMapping(partner.partner_id)); const [loading, setLoading] = useState(false);
  useEffect(() => { setForm(defaultMapping(partner.partner_id)); loadRows(); }, [partner.partner_id]);
  async function loadRows() { try { setLoading(true); const res = await apiFetch(`${API_BASE}/${encodeURIComponent(partner.partner_id)}/mappings`, { method: "GET" }); if (!res.ok) throw new Error(await parseApiError(res)); const data = await res.json(); setRows(Array.isArray(data) ? data : []); } catch (err: any) { onBanner(err?.message || "Failed to load mappings."); } finally { setLoading(false); } }
  async function saveRow() { try { const res = await apiFetch(`${API_BASE}/mappings`, { method: "POST", body: JSON.stringify({ ...form, partner_id: partner.partner_id }) }); if (!res.ok) throw new Error(await parseApiError(res)); onBanner("Mapping saved successfully."); setForm(defaultMapping(partner.partner_id)); await loadRows(); } catch (err: any) { onBanner(err?.message || "Unable to save mapping."); } }
  return <div style={card}><div style={title}>Field Mapping</div><div style={grid}>{field("Source Field", <input value={form.source_field} onChange={(e) => setForm({ ...form, source_field: e.target.value })} style={input} />)}{field("Target Field", <input value={form.target_field} onChange={(e) => setForm({ ...form, target_field: e.target.value })} style={input} />)}{field("Transform Type", <select value={form.transform_type} onChange={(e) => setForm({ ...form, transform_type: e.target.value })} style={input}><option value="DIRECT">DIRECT</option><option value="DEFAULT">DEFAULT</option><option value="LOOKUP">LOOKUP</option><option value="CONCAT">CONCAT</option><option value="FORMULA">FORMULA</option></select>)}</div><div style={{ display: "flex", gap: 10, marginTop: 14 }}><button type="button" style={primaryButton} onClick={saveRow}>Save Mapping</button></div><div style={{ overflowX: "auto", marginTop: 16 }}><table style={tableStyle}><thead><tr><th style={thStyle}>Source Field</th><th style={thStyle}>Target Field</th><th style={thStyle}>Transform Type</th><th style={thStyle}>Active</th></tr></thead><tbody>{loading ? <tr><td colSpan={4} style={tdEmptyStyle}>Loading...</td></tr> : rows.length === 0 ? <tr><td colSpan={4} style={tdEmptyStyle}>No mappings configured.</td></tr> : rows.map((row) => <tr key={row.mapping_id}><td style={tdStyle}>{row.source_field}</td><td style={tdStyle}>{row.target_field}</td><td style={tdStyle}>{row.transform_type}</td><td style={tdStyle}>{row.is_active ? "YES" : "NO"}</td></tr>)}</tbody></table></div></div>;
}
function field(label: string, child: React.ReactNode) { return <div><div style={labelStyle}>{label}</div>{child}</div>; }
const card: React.CSSProperties = { border: "1px solid #eef2f7", borderRadius: 12, background: "#fff", padding: 16 };
const title: React.CSSProperties = { fontSize: 15, fontWeight: 800, color: "#0f172a", marginBottom: 14 };
const grid: React.CSSProperties = { display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 14 };
const labelStyle: React.CSSProperties = { fontSize: 12, fontWeight: 700, color: "#475569", marginBottom: 6 };
const input: React.CSSProperties = { width: "100%", minHeight: 38, padding: "8px 10px", borderRadius: 8, border: "1px solid #dbe4ee", background: "#fff", fontSize: 13, color: "#0f172a", outline: "none", boxSizing: "border-box" };
const primaryButton: React.CSSProperties = { border: "1px solid #0b5fff", background: "#0b5fff", color: "#fff", borderRadius: 8, padding: "9px 14px", fontSize: 13, fontWeight: 700, cursor: "pointer" };
const tableStyle: React.CSSProperties = { width: "100%", borderCollapse: "collapse", marginTop: 12 };
const thStyle: React.CSSProperties = { textAlign: "left", padding: "10px 12px", fontSize: 12, fontWeight: 800, color: "#334155", borderBottom: "1px solid #e5e7eb", background: "#f8fafc", verticalAlign: "top" };
const tdStyle: React.CSSProperties = { padding: "10px 12px", fontSize: 13, color: "#0f172a", borderBottom: "1px solid #eef2f7", verticalAlign: "top" };
const tdEmptyStyle: React.CSSProperties = { padding: "16px 12px", fontSize: 13, color: "#64748b", borderBottom: "1px solid #eef2f7" };
