export type TradingPartnerUomRule = {
  uom_rule_id?: string;
  client_id: string;
  partner_id: string;
  sold_to?: string | null;
  ship_to?: string | null;
  material_code?: string | null;
  product_code?: string | null;
  input_uom: string;
  output_uom: string;
  conversion_factor?: string | number | null;
  conversion_divider?: string | number | null;
  rounding_digits: number;
  rounding_mode: string;
  min_quantity?: string | number | null;
  max_quantity?: string | number | null;
  priority: number;
  is_active: boolean;
  notes?: string | null;
  created_by?: string | null;
  updated_by?: string | null;
  created_at?: string;
  updated_at?: string;
};

export type TradingPartnerBusinessRule = {
  rule_id?: string;
  client_id: string;
  partner_id: string;
  rule_name: string;
  rule_type: string;
  document_type: string;
  message_direction: string;
  sold_to?: string | null;
  ship_to?: string | null;
  material_code?: string | null;
  condition_json: Record<string, any>;
  action_json: Record<string, any>;
  priority: number;
  stop_on_match: boolean;
  is_active: boolean;
  notes?: string | null;
  created_by?: string | null;
  updated_by?: string | null;
  created_at?: string;
  updated_at?: string;
};

export type TradingPartnerMappingProfile = {
  mapping_profile_id?: string;
  client_id: string;
  partner_id: string;
  profile_name: string;
  document_type: string;
  input_format: string;
  source_channel?: string | null;
  sold_to?: string | null;
  ship_to?: string | null;
  field_mapping_json: Record<string, any>;
  header_defaults_json: Record<string, any>;
  line_mapping_json: Record<string, any>;
  validation_json: Record<string, any>;
  layout_hint_json: Record<string, any>;
  ai_prompt_override?: string | null;
  version_no: number;
  priority: number;
  is_default: boolean;
  is_active: boolean;
  notes?: string | null;
  created_by?: string | null;
  updated_by?: string | null;
  created_at?: string;
  updated_at?: string;
};

export type TradingPartnerOnboardingAudit = {
  audit_id: string;
  client_id: string;
  partner_id: string;
  entity_type: string;
  entity_id: string;
  action: string;
  before_json?: Record<string, any> | null;
  after_json?: Record<string, any> | null;
  actor_email?: string | null;
  actor_role?: string | null;
  remarks?: string | null;
  created_at: string;
};
